# Generated by Django 3.2.5 on 2021-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210717_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprojects',
            name='projects',
            field=models.FileField(upload_to=''),
        ),
    ]
