# Generated by Django 3.2.5 on 2021-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_postprojects_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('bio', models.TextField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
